### ISSUE TITLE
Glory's Introduction

### ISSUE THREAD

**Issue by GloryCee** [oppia/lessons-team#1003]
Hello everyone, I'm so excited to be here. This is a very special opportunity for me. My name is Glory and I'm a product manager and teacher. 
I'm excited to be contributing with a lot of smart people, I wish us the best!

**Comment by Influencer07** [comment]
Welcome @GloryCee, nice to have you here

Use the "discussions" tab for all kind of discussions. The "issues" tab is to record issues that requires the attention of the developers, or facilitators of Oppia projects.

See #933 for information on how to use the appropraite channels for discussion.


I hope this was helpful.

**Comment by GloryCee** [comment]
@Influencer07 thank you for this. I don't know how to use the discussion tab to make a post, I'm finding it hard to navigate. Please can you assist?

**Comment by Hasoye** [comment]
@GloryCee when you are on the discussion tab, first check previous discussion if the questions you have has been asked before, if the question has not been asked before, you will see a button, ´new discussion ‘…click on it to start a discussion alright👍

**Comment by GloryCee** [comment]
@Hasoye thank you!

**Comment by Hasoye** [comment]
You are welcome @GloryCee …if you encounter a roadblock, you can always ask questions, we are here for each other🤗

**Comment by seanlip** [comment]
Hi folks -- please use [Discussions](https://github.com/oppia/lessons-team/discussions) for introductions. Issues should only be used for reporting bugs or problems in the content, or things that need to be fixed. Thanks!
