### ISSUE TITLE
Afoma's introduction

### ISSUE THREAD

**Issue by Afoma-Egbuonu** [oppia/lessons-team#1010]
Hello everyone, My name is Afoma Egbuonu. I am a Teacher and a Product Manager. It is so good to be here.

**Comment by Influencer07** [comment]
Welcome @Afoma-Egbuonu , nice to have you here

Use the "discussions" tab for all kind of discussions. The "issues" tab is to record issues that requires the attention of the developers, or facilitators of Oppia projects.

See https://github.com/oppia/lessons-team/discussions/933 for information on how to use the appropraite channels for discussion.

I hope this was helpful.

**Comment by seanlip** [comment]
Hi folks -- as @Influencer07 says, please use [Discussions](https://github.com/oppia/lessons-team/discussions) for introductions. Issues should only be used for reporting bugs or problems in the content, or things that need to be fixed. Thanks!
