### ISSUE TITLE
Irene's introduction

### ISSUE THREAD

**Issue by IreneAnyadu** [oppia/lessons-team#1025]
Hello everyone.
I am Irene Anyadu, a graphic designer and digital artist. I hope everyone is having a lovely day. I am happy to be here and look forward to contributing to this project.

**Comment by pholhuche** [comment]
It is great to have you, welcome

**Comment by IreneAnyadu** [comment]
Thank you!

**Comment by seanlip** [comment]
Hi folks -- please use [Discussions](https://github.com/oppia/lessons-team/discussions) for introductions. Issues should only be used for reporting bugs or problems in the content, or things that need to be fixed. Thanks!
