### ISSUE TITLE
Asking About Mentorship 

### ISSUE THREAD

**Issue by JenniferOgwuche** [oppia/lessons-team#1057]
Am I supposed to connect with my mentor before embarking on any project/task/contribution? If yes, can it be on here or would it be via emails? I just want to make make I'm doing the right thing or following the right protocols.

**Comment by Obiadada** [comment]
Hello Jennifer, I guess you should embark on your task while waiting for our mentor.
I hope this helps.

**Comment by JenniferOgwuche** [comment]
> Hello Jennifer, I guess you should embark on your task while waiting for our mentor. I hope this helps.

Thank you so much with this. I really appreciate.

**Comment by JenniferOgwuche** [comment]
Hello @Obiadada
Thank you so much for clearing my curiosity. I really do appreciate

**Comment by seanlip** [comment]
Hi folks -- please use [Discussions](https://github.com/oppia/lessons-team/discussions) for introductions and questions. Issues should only be used for reporting bugs or problems in the lesson content, or things that need to be fixed. Thanks!

**Comment by JenniferOgwuche** [comment]
@seanlip

Alright. Noted. Thank you!

**Comment by Obiadada** [comment]
Please pardon me, it wasn't intentional.
