### ISSUE TITLE
Chapters For Length Measurement Topic are Missing On Oppia Website

### ISSUE THREAD

**Issue by Judith0001** [oppia/lessons-team#1482]
The chapters or lessons under Length Measurement topic aren't coming up on the [Oppia website](https://www.oppia.org/learn/math/length-measurements). Please find the screenshot below:

![Screenshot (82)](https://github.com/user-attachments/assets/4f3d5032-0d0b-4d5d-9144-4c5876ec2a05)

Thank you.

**Comment by seanlip** [comment]
This seems to be working correctly now -- closing as fixed. Thanks for reporting @Judith0001!
