### ISSUE TITLE
[BUG]: Text formatting issue on several cards in the 'Forms of money' lesson

### ISSUE THREAD

**Issue by Nooraw** [oppia/lessons-team#1575]
### Describe the bug

There are several cards with text formatting issues in Chapter 3(Forms of Money) under the topic 'Money'. The words in certain sentences are not spaced properly, thereby affecting readability and can be confusing for some learners. 

### URL of the page where the issue is observed.

https://www.oppia.org/explore/R266glKs5vu0?collection_id=YDlsNsQItZiE

### Steps To Reproduce

1. Click the link to go to the lesson
2.  Slide through the all cards under the lesson

### Expected Behavior

You will come across several cards with certain words clumped together without spacing. I have attached screenshots of all the cards where this issue occurs.

### Screenshots/Videos

![issue1](https://github.com/user-attachments/assets/f6344aea-578d-4888-86c9-02b0635c53f4)
![issue2](https://github.com/user-attachments/assets/4a84e232-aad4-4332-b37c-42546eb6d055)
![issue3](https://github.com/user-attachments/assets/5f060afb-1839-40c4-8890-7775da8c33d9)
![issue4](https://github.com/user-attachments/assets/86b963c8-ee1e-46be-b2be-1fd2c30deb53)
![issue5](https://github.com/user-attachments/assets/f6f11890-b762-4722-b87f-b55d91f2235c)
![issue6](https://github.com/user-attachments/assets/d956bb39-4721-44a2-874d-ef8f23186064)
![issue7](https://github.com/user-attachments/assets/93308b75-0568-4590-b668-3c7f7d9061c9)
![issue8](https://github.com/user-attachments/assets/93a8b15d-6011-44aa-a00f-eaf95b12bbb9)
![issue9](https://github.com/user-attachments/assets/8b2013e0-92f6-49a2-847e-60e16d9e72c4)
![issue10](https://github.com/user-attachments/assets/a09872f7-eab6-4737-8531-0bbd47660d73)
![issue11](https://github.com/user-attachments/assets/a7201d7d-de76-4911-bab9-1367ec2b5220)
![issue12](https://github.com/user-attachments/assets/cd8bc722-a817-41f6-9990-4c7c24e0a030)
![issue13](https://github.com/user-attachments/assets/55d978f7-fabf-49ec-a4e2-d5237b202deb)

### What device are you using?

Desktop

### Operating System

Windows

### What browsers are you seeing the problem on?

Chrome

### Tips for developers

Before addressing the bug, please identify which PR caused the issue (you can follow the steps [here](https://github.com/oppia/oppia/wiki/How-to-find-the-commit-which-introduced-a-bug)). If you identify the PR, comment on the issue with a link to it. If not, mention the commit hash of the oldest commit you saw the bug on (and the month and year it was made in).

Then, please leave a comment with details of the approach that you plan to take to fix the issue (see [example](https://github.com/oppia/oppia/issues/19157#issuecomment-1858788463)).

**Note:** If this is your first Oppia issue, please make sure to follow our guidelines for [choosing an issue](https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#choosing-a-good-first-issue) and [setting things up](https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#setting-things-up). You will also need to show a demo of the fix working correctly on your local machine. Thanks!

**Comment by seanlip** [comment]
@Kebith PTAL and leave a comment on the thread when this is fixed, thanks!

**Comment by Kebith** [comment]
@seanlip This has been fixed now. Thanks!
