### ISSUE TITLE
Issues with forms on Length Measurements

### ISSUE THREAD

**Issue by Daodu111** [oppia/lessons-team#1576]
I am an Outreachy applicant, I want to report an issue with the [submission form](https://docs.google.com/forms/d/e/1FAIpQLSfMZ-6W9MSw5r5Nch66rCPCPh7R4PIqELRc-XQ1Hw_9KR_YqQ/viewform) in the [Research Plan -- Effectiveness of Basic Math Lessons](https://docs.google.com/document/d/1j1S9HnoesGZMNeYccV8rXZ2bZwPhKV5-B6j9CnPRM_I/edit?tab=t.0). There is no topic called '[Length Measurement](https://www.oppia.org/learn/math/length-measurements/story/track-and-field)' as this is the topic that is allowed for us to research on. 

Also, I want to report the same issue for the student Post survey form - 
https://docs.google.com/forms/d/e/1FAIpQLSc0AAzVMmqTMfDlbTDrSRcla5Ai7uujXKJRJ_D9b-foFzarlQ/viewform

The learners are unable to fill out the form as the topic they learned is not there. I am also unable ti fill in the submission form because of the same issue.

**Comment by PrettyNneoma** [comment]
Hi @Daodu111 This is now fixed. Thanks for filing this issue and sorry for any inconvenience caused.
