### ISSUE TITLE
Issue with Post-Test question on Length Measurements

### ISSUE THREAD

**Issue by Daodu111** [oppia/lessons-team#1611]
The answers for question 8 and 10 for the post test questions are incorrect. The answer in the [spreadsheet](https://docs.google.com/spreadsheets/d/1p_SVXfFX7DbK04Muv06-tMGNOEo1nbdH5SWsR8cJO7k/edit) for question 8 is 1.22m instead of 3.658 meteres, also the answer for question 10 is 36cm2 instead of 36 square inches. 

KIndly help me look into it. Thank you.

**Comment by seanlip** [comment]
Thanks for reporting @Daodu111. @Kebith has let me know that she's fixed this in the spreadsheet, so I'm closing this issue as completed. Please let us know if there is anything else that needs to be updated. 

Thanks!
