### ISSUE TITLE
[BUG]: ANSWER MISMATCH: Incorrect options marked as correct in Oppia quizes

### ISSUE THREAD

**Issue by phenomenal-dev** [oppia/lessons-team#1640]
### Describe the bug

When I click the right answer, it gets marked as wrong and when I pick the wrong answer, it gets marked as right.

### URL of the page where the issue is observed.

https://www.oppia.org/explore/z3wkM0ua9JJL?collection_id=rCxL3LRoFPKh

### Steps To Reproduce

1. Access the lesson chapter [here](https://www.oppia.org/explore/z3wkM0ua9JJL?collection_id=rCxL3LRoFPKh)
2. Proceed to the final question
3. Click on "The image of a boy with chicken pox and spots on his body"
4. See Error

### Expected Behavior

It's expected to give a feedback to show you're correct.

### Screenshots/Videos

![Screenshot (126)](https://github.com/user-attachments/assets/48517903-7f01-4060-b47f-4b6525a63a30)

### What device are you using?

Desktop

### Operating System

Windows

### What browsers are you seeing the problem on?

Chrome

### Browser version

Version 129.0.6668.103 (Official Build) (64-bit)

### Tips for developers

Before addressing the bug, please identify which PR caused the issue (you can follow the steps [here](https://github.com/oppia/oppia/wiki/How-to-find-the-commit-which-introduced-a-bug)). If you identify the PR, comment on the issue with a link to it. If not, mention the commit hash of the oldest commit you saw the bug on (and the month and year it was made in).

Then, please leave a comment with details of the approach that you plan to take to fix the issue (see [example](https://github.com/oppia/oppia/issues/19157#issuecomment-1858788463)).

**Note:** If this is your first Oppia issue, please make sure to follow our guidelines for [choosing an issue](https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#choosing-a-good-first-issue) and [setting things up](https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#setting-things-up). You will also need to show a demo of the fix working correctly on your local machine. Thanks!

**Comment by seanlip** [comment]
Hi @phenomenal-dev, thanks for reporting this. I have reported it to Aanu and she has fixed it! If you could, would you mind taking a look again and letting us know if things are good now, or if there are any other issues that need to be addressed?

Thank you!

**Comment by phenomenal-dev** [comment]
Hello @seanlip, I just confirmed and it's working fine now

**Comment by seanlip** [comment]
Great -- thanks!
