### ISSUE TITLE
[BUG]: Difficulty signing in on website

### ISSUE THREAD

**Issue by Sage-Hermit** [oppia/lessons-team#573]
I have been unable to sign in for the past one hour it keeps loading and returning back to the homepage and I used it earlier today, can this be looked into?

**Comment by Chidinma-Egwuogu** [comment]
Hi @Sage-Hermit, this might not be the right place to raise issues. The Outreachy/Oppia Project Site says issues should be raised here: https://github.com/oppia/oppia/issues

**Comment by Sage-Hermit** [comment]
I figure and raised it there. Thanks.

**Comment by PasunuriSrinidhi** [comment]
Cached data and cookies can sometimes cause login issues on websites. Try clearing your browser's cache and cookies, and then try logging in again.

**Comment by seanlip** [comment]
I think this should be fixed, but please reopen if you're still having issues. Thanks!
