### ISSUE TITLE
Incorrect number is read by voiceover for a question in What is the placevalue

### ISSUE THREAD

**Issue by KolliAnitha** [oppia/lessons-team#643]
**Describe the bug**
Incorrect number is read by voiceover for a question in What is the placevalue

**To Reproduce**
1. Go to 'Place Values' - What is the Placevalue
2. Click on 'Continue' till you reach the question 'In the number 5971 which number is in tens place'
3. Tap on the Audio button
4. Listen to the Audio

**Expected behavior**
The voiceover should read The number 5971 instead of 5921 

**Demonstration**
![Screenshot_2022-09-10-20-57-57-31_943a62cb4c6fb83e010e1c2e82766a17.jpg](https://user-images.githubusercontent.com/101634267/189490668-61f23cad-188d-4e7f-8ede-3c16c08456ef.jpg)

**Environment**
Mobile: One Plus Nord2 5G
Android Version: 11
App Version: 0.9-beta-3f935261e0

**Comment by BenHenning** [comment]
Hmm, this is rather odd. I'm not sure why Talkback would read the wrong number, so we'll need to try and repro this locally to investigate it.

**Comment by BenHenning** [comment]
Ah I misunderstood the issue. This seems like a content issue.

**Comment by rt4914** [comment]
Possible Duplicate oppia/lessons-team#442

**Comment by Kebith** [comment]
From the lesson review team, confirming this has been fixed. Voiceover reads the digit correctly in the app version 0.12-beta-01f4111508
