### ISSUE TITLE
[Feature Request]: Replace "Placeholder Text" with "Enter Answer "

### ISSUE THREAD

**Issue by rufaida99-k** [oppia/lessons-team#703]
### Is your feature request related to a problem? Please describe.

In certain lessons, when you try to go through a lesson, and you are prompted to answer a question, the answer bar says "Placeholder text". I propose we can change it to something like "Enter answer"

![image](https://user-images.githubusercontent.com/112827402/230809273-417a2ef2-e081-4594-8fdc-7c1a72d0c7f7.png)

### Describe the solution you'd like

Change the "Placeholder text" to "Enter Answer: " instead.

<img width="729" alt="image" src="https://user-images.githubusercontent.com/112827402/230811495-c272654e-5a10-4e78-90b8-c4241079798b.png">

**Comment by CJFelton** [comment]
I replaced all of the placeholder text throughout each Decimals topic.
