### ISSUE TITLE
[BUG]: No feedback displayed after submitting wrong answer

### ISSUE THREAD

**Issue by Giftedgrace** [oppia/lessons-team#704]
### Describe the bug

While going through this lesson Decimals, I inputted a wrong answer in an attempt to answer a question and there was no feedback from Oppia and I was moved immediately to the next card without clicking on the continue button. The correct answer though worked as expected.

### Steps To Reproduce

Go to decimals chapter 2: Decimal Place Values see the link here https://www.oppia.org/create/YnhDmpzewUYI?story_url_fragment=reena-race&topic_url_fragment=decimals&classroom_url_fragment=math&node_id=node_5 select the 'Test' card.

### Expected Behavior

I expected Oppia to give me a feedback like incorrect answer, try again and an opportunity to attempt the question once again. 

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/32488644/229291872-07768d83-76ab-4cad-9b95-5ac6ea828c4f.png)

![image](https://user-images.githubusercontent.com/32488644/229291812-3c8795ab-fe41-4b7b-b531-bb08a9f9d443.png)

![image](https://user-images.githubusercontent.com/32488644/229291912-ac089730-332e-45be-87f8-fd10712d7370.png)

### What device are you using?

Desktop

### Operating System

Windows

### What browsers are you seeing the problem on?

Chrome

### Browser version

Version 111.0.5563.146 (Official Build) (64-bit)

**Comment by CJFelton** [comment]
I fixed this issue, it now displays text.
