### ISSUE TITLE
The answer options for some of the questions in Chapter 3(Comparing Numbers) of the Lesson Place Values are wrong which can confuse learners.

### ISSUE THREAD

**Issue by Adefeyisayo** [oppia/lessons-team#710]
**Describe the bug**
Chapter 3 of Lesson Topic Place Value have the wrong answers listed as options which is confusing to the learner.

**To Reproduce**
1. Go to "Home, select a topic to start"
2. Click on "Place Values"
3. Start a lesson "Chapter 3"
4. Check the answer options

**Expected behavior**
The options in the questions are different from the options in the answers section

**Demonstration**
![image](https://user-images.githubusercontent.com/105318377/202925543-94c01961-5973-4c3e-a364-d583862f3b56.png)

**Environment**
- Device/emulator being used: Smartphone
- Android or SDK version: Android
- App version : 0.9-beta-3f935261e0

**Comment by BenHenning** [comment]
@Adefeyisayo could you perhaps fill in some of the fields in the opening comment template to provide additional context? Without that, it's hard to actually triage and work on this issue.

**Comment by Adefeyisayo** [comment]
I am so sorry it's coming late. The issue has been updated.

**Comment by BenHenning** [comment]
Ah nice catch. Thanks @Adefeyisayo for updating the main comment--this is really helpful!

Routing over to the content team to triage.

**Comment by seanlip** [comment]
This has been fixed in the lesson. Thanks for reporting @Adefeyisayo !
