### ISSUE TITLE
Chapters 2,3 and 4 under the Topic lesson place values have different texts from the voice over.

### ISSUE THREAD

**Issue by Adefeyisayo** [oppia/lessons-team#711]
**Describe the bug**
The voice over in the topic lesson place values for chapters 2, 3 and 4 do not correspond from the readable text lessons.

**To Reproduce**
1. Go to ''Home, select a topic"
2. Click on "Place Values"
3. Start a lesson "Chapter 2,3,4"
4. Click on the audio icon

**Expected behavior**
The audio translation is saying something different from the text lessons which is wrong.

**Demonstration**
![image](https://user-images.githubusercontent.com/105318377/202924839-8ec4d36c-3aa9-49d9-9a7d-cdc413928df1.png)
![image](https://user-images.githubusercontent.com/105318377/202924857-a6861019-046e-4cde-9b0d-178c978bccc8.png)

**Environment**
- Device/emulator being used: Smartphone
- Android or SDK version : Android
- App version: 0.9-beta-3f935261e0

**Comment by BenHenning** [comment]
@Adefeyisayo could you perhaps fill in some of the fields in the opening comment template to provide additional context? Without that, it's hard to actually triage and work on this issue.

**Comment by Adefeyisayo** [comment]
I am so sorry for the delay. The issue has been updated.

**Comment by BenHenning** [comment]
Thanks @Adefeyisayo! Routing over to the content team.

**Comment by klin5595** [comment]
This is solved!
