### ISSUE TITLE
Spelling errors in Nigerian Pidgin translation of Chapter 1 of Place Values

### ISSUE THREAD

**Issue by Kebith** [oppia/lessons-team#721]
Text reads “Also, , ek yu get…”

The translation in Nigerian pidgin should be corrected as “Also, if yu get paper and pen…”
Note that audio translation reads the correction I suggested above

![Screenshot 2022-10-18 at 17-41-35 What are the Place Values](https://user-images.githubusercontent.com/111491620/196491796-296b07e1-0ccc-4c90-aa8e-211d79c1bfa8.png)

**Comment by U8NWXD** [comment]
@seanlip another content bug

**Comment by seanlip** [comment]
This has been fixed. Sorry for the delay!
