### ISSUE TITLE
Image size is too big in the first page of What is a fraction chapter

### ISSUE THREAD

**Issue by KolliAnitha** [oppia/lessons-team#722]
**Describe the bug**
Image size is too big in the first page of What is a fraction chapter

**To Reproduce**
 1. Login to oppia.org
 2. Go to 'Learn' - Click on Fractions
 3. In Lessons, click on What is Fraction
 5. See the image 

**Observed behavior**
Image size is too big compared to other images in the chapter

**Expected behavior**
Image size should be nominal like the images in other pages

**Screenshots / Videos**
oppia.org image:
![Screenshot 2022-08-18 2 08 39 PM](https://user-images.githubusercontent.com/101634267/185350796-81fb96d7-1a84-4f42-842c-7ba6c80a143d.png)
 
oppiatestserver.org
![Screenshot 2022-08-18 8 55 28 AM](https://user-images.githubusercontent.com/101634267/185350938-e5380fa8-0489-4a07-9ec7-f8f7ea06611c.png)

**Desktop (please complete the following information; delete this section if the issue does not arise on desktop):**
 - OS: chromebook
 - Browser: chrome
 - Browser-version: 104.0.5112.83

**Comment by Dorothy2020** [comment]
Hello, @kevintab95  can I be assigned to solve the issue

**Comment by seanlip** [comment]
The image size has been reduced:

![Screenshot from 2024-03-18 23-12-11](https://github.com/oppia/lessons-team/assets/10575562/df895431-9ff8-4a40-bfa0-b52f475ab380)
