### ISSUE TITLE
Concerning the recording for task 1

### ISSUE THREAD

**Issue by Chy-baby** [oppia/lessons-team#780]
How do we record the session? Is it while interviewing the student and after the interview should we stop recording or we should continue the recording while they are learning on the oppia website? I need clearity on this because my session is one on one session it's not virtual.

**Comment by Ayesh-07** [comment]
Certainly! Here's a concise version:

1. Start recording at the beginning of the session and stop at the end.
2. If there's an interview, record that part with the student's consent.
3. You can choose to record the student learning on Oppia, but ensure it doesn't disrupt their learning.
4. Discuss the recording process with the student before the session.
5. Respect the student's privacy and preferences regarding recording.

**Comment by Ayesh-07** [comment]
Dear Chy-baby! 
I'm Ayesha Nudrat .I am a candidate for the Outreachy program in May 2024, with nearly five years of teaching experience.

Start recording at the beginning of the session and stop at the end.
If there's an interview, record that part with the student's consent.
You can choose to record the student learning on Oppia, but ensure it doesn't disrupt their learning.
Discuss the recording process with the student before the session.
Respect the student's privacy and preferences regarding recording.

**Comment by seanlip** [comment]
This isn't an issue with the platform/lessons, so I'm closing it.

For future reference, please use the DIscussions threads for questions like this. Thanks.
