### ISSUE TITLE
Question on Task 3: lesson Review Docs

### ISSUE THREAD

**Issue by funmbiroyal** [oppia/lessons-team#894]
Hello everyone. please I have a concern on task 3 and I have been on it for days. I mean this part

"Afterwards, play through 5 or more lessons from the topics: Decimals, Geometry, on the Oppia website [here](https://www.oppia.org/learn/math), Hygiene and Diseases [here](https://www.oppia.org/collection/rCxL3LRoFPKh), Matter [here](https://www.oppia.org/collection/Qd3ijnkSx3Iv), and Scientific Principles [here](https://www.oppia.org/collection/lXh1r87b7NGK)."

We were told to play 5 lessons or more from each of the topics listed above and give a review.
Now my first question is Must it be a negative review? (Because from the submission template it was written that we should give negative notes) for me there were lessons i have played and carefully checked and i did not see any negatives with them.  and Task was also saying our review must be 5 lessons or more for each topic and our reviews must not be scanty. Please I am confused. @Kebith can you please say something ??
2nd question: must we review 5 lessons for all the topics? What if I see nothing wrong in some of the lessons after reviewing? is it fine to give positive feedbacks or i should just leave the lessons that seems fine to me without writing a report. infact i just finished reviewing a lesson now under Matter and Non-Matter, and honestly I see nothing wrong with it. please I don't know what to do, because I am confused! Thanks

**Comment by seanlip** [comment]
This isn't an issue with the platform/lessons, so I'm closing it.

For future reference, please use the DIscussions threads for questions like this. Thanks.
