### ISSUE TITLE
[BUG]: Character name is inconsistent

### ISSUE THREAD

**Issue by juliafalarini** [oppia/lessons-team#932]
### Describe the bug

For the Fraction lessons, the name of the main character is being used sometimes as Matthew, and sometimes as Mateus, in Brazilian Portuguese. We should be consistent and preferably use only Mateus, since it's a Portuguese name.

<img width="814" alt="image" src="https://github.com/oppia/oppia/assets/92189102/7d86a8f6-1246-498e-bcb9-440a41174878">

### URL of the page where the issue is observed.

https://www.oppia.org/learn/math/fractions/story/matthew-visits-the-bakery

### Steps To Reproduce

Access the [link](https://www.oppia.org/learn/math/fractions/story/matthew-visits-the-bakery)
View the issue on the title and chapter description.

### Expected Behavior

Use the name Mateus consistently in the chapter descriptions, within the story and in the story title.

### Operating System

MacOS

### What browsers are you seeing the problem on?

Chrome

### Browser version

 119.0.6045.159

### Tips for developers

Before tackling the bug, please use `git bisect` (see https://git-scm.com/docs/git-bisect) to investigate which PR caused it (you only need to go back as far as commit https://github.com/oppia/oppia/commits/9a334e9). If you find the PR, leave a comment on this issue pointing to it, or just say that it happened before commit 9a334e9 if you could reproduce it there. This will help us fix the issue by reverting the faulty PR.

Also, if this is your first issue, please make sure to follow https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#choosing-a-good-first-issue and https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#setting-things-up before claiming it. Thanks!

**Comment by sivangbagri** [comment]
Hii @juliafalarini , I would like to solve this issue , please assign me this issue.

**Comment by seanlip** [comment]
@sivangbagri This is actually an issue for the lessons team, not the technical team, so I'm moving it there.

@juliafalarini This can actually be fixed by the translators on translatewiki (and on the exploration translation pages), FYI.

**Comment by juliafalarini** [comment]
I've updated the name of the lessons, and i've sent an email to Vanessa and Giovanna (translation coordinators) so they can update the lessons content accordingly. I think this can be closed, thanks!

**Comment by seanlip** [comment]
Awesome, thanks @juliafalarini! Closing this then :)

**Comment by seanlip** [comment]
P.S. Could you please cc me on the email sent to Vanessa/Giovana? Thanks!

**Comment by juliafalarini** [comment]
@seanlip done, thanks
